#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 12 16:02:37 2021

@author: ert
"""
from scraper import stockScraper, liveStockScraper
from database import stockDatabaseOperator
from config.static_vars import STOCK_HISTORY_PATH, DEBUG, DAY_ZERO
from utils.datetime_tools import get_delta_date, get_today_date
from schedule_maker.bg_schedule import scheduler
from gibber import gabber

her_operator = stockDatabaseOperator(STOCK_HISTORY_PATH)
her_scraper = stockScraper()
her_live_scraper = liveStockScraper()

all_codes = her_operator.get_all_codes()
all_open_days = her_scraper.get_open_days("2021-01-01", "2021-12-07")

f_in = open("/home/ert/Desktop/profit1.csv", "w", encoding="utf-8")
f_in.write("code,date,label,scene,ratio,i\n")
f_in.close()

f_in3 = open("/home/ert/Desktop/profit7.csv", "w", encoding="utf-8")
f_in3.write("code,date,label,scene,ratio,i\n")
f_in3.close()

f_in4 = open("/home/ert/Desktop/profit14.csv", "w", encoding="utf-8")
f_in4.write("code,date,label,scene,ratio,i\n")
f_in4.close()


f_in2 = open("/home/ert/Desktop/temp_feature.csv", "w", encoding="utf-8")
f_in2.write("code,feature\n")


dataset1 = list()
dataset7 = list()
dataset14 = list()

for cidx, code in enumerate(all_codes):
    code = code[0]
    print(f"doing {code}, {cidx}")
    table_name = her_operator._table_dispatch(code, _type="day")
    record = her_operator.fetch_by_command(
        "SELECT {} FROM '{}' \
        WHERE code='{}' AND tradestatus='1';".format(
            ",".join(["date", "turn", "pctChg", "peTTM"]), table_name, code
        ),
    )
    seq = list()
    turns, pcts, pets = list(), list(), list()
    ratio = 1
    for date, turn, pct, pettm in record:
        if pct == "":
            continue
        ratio *= 1 + pct / 100
        seq.append(round(ratio, 4))
        turns.append(turn)
        pcts.append(pct)
        pets.append(pettm)

    feature = {
        "turn30": turns,
        "pct30": pcts,
        "pet30": pets,
    }
    f_in2.write(code + "," + str(feature) + "\n")

    for i, ratio in enumerate(seq):
        if i < 30 or i >= len(seq) - 14:
            continue
        day10 = seq[i + 10]
        day5 = seq[i + 5]
        day1 = seq[i + 1]
        day0 = seq[i]
        date = record[i][0]

        if day10 > day5 > day0:
            label = "1"
            if day10 - day0 > 0.1:
                label = "2"
        elif day10 < day5 < day0:
            label = "-1"
            if day10 - day0 < -0.05:
                label = "-2"
        else:
            label = "0"

        dataset14.append(
            ",".join([code, date, label, "14", str(day10 - day0)[:6], str(i)]) + "\n"
        )

        if day5 > day1 > day0:
            label = "1"
            if day5 - day0 > 0.1:
                label = "2"
        elif day5 < day1 < day0:
            label = "-1"
            if day5 - day0 < -0.05:
                label = "-2"
        else:
            label = "0"

        dataset7.append(
            ",".join([code, date, label, "7", str(day5 - day0)[:6], str(i)]) + "\n"
        )

        if day1 > day0:
            label = "1"
            if day1 - day0 > 0.1:
                label = "2"
        elif day1 < day0:
            label = "-1"
            if day1 - day0 < -0.05:
                label = "-2"
        else:
            label = "0"

        dataset1.append(
            ",".join([code, date, label, "1", str(day1 - day0)[:6], str(i)]) + "\n"
        )

    if len(dataset1) >= 10000:
        f_in1 = open("/home/ert/Desktop/profit1.csv", "a", encoding="utf-8")
        f_in1.writelines(dataset1)
        f_in.close()
        dataset1.clear()
        f_in14 = open("/home/ert/Desktop/profit14.csv", "a", encoding="utf-8")
        f_in14.writelines(dataset14)
        f_in14.close()
        dataset14.clear()
        f_in7 = open("/home/ert/Desktop/profit7.csv", "a", encoding="utf-8")
        f_in7.writelines(dataset7)
        f_in7.close()
        dataset7.clear()

f_in1 = open("/home/ert/Desktop/profit1.csv", "a", encoding="utf-8")
f_in1.writelines(dataset1)
f_in.close()
dataset1.clear()
f_in14 = open("/home/ert/Desktop/profit14.csv", "a", encoding="utf-8")
f_in14.writelines(dataset14)
f_in14.close()
dataset14.clear()
f_in7 = open("/home/ert/Desktop/profit7.csv", "a", encoding="utf-8")
f_in7.writelines(dataset7)
f_in7.close()
dataset7.clear()

f_in2.close()
"""
{code:[(timestamp, features, ratio, label)]

"""
